name: saathi
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
flutter:
  uses-material-design: true
  assets:
    - assets/images/saathi.png
    - assets/images/linkedin.png
    - assets/images/instagram.png
    - assets/images/facebook.png
    - assets/images/twitter.png
    - assets/images/expert_local_guides.png
    - assets/images/Comfortable Accommodations.png
    - assets/images/Adventure Activities.png
    - assets/images/Safety and Convenience.png
    - assets/images/Etiosdesire.jpg
    - assets/images/Scorpio.jpg
    - assets/images/Tempo Traveler.jpg
    - assets/images/Innova.jpg
    - assets/images/profilepreview.jpg

  fonts:
    - family: Utendo
      fonts:
        - asset: assets/fonts/Utendo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Utendo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Utendo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Utendo-Semibold.ttf
          weight: 600